FROM node:20-slim as builder
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
ENV WORKDIR=/fyp_web

WORKDIR $WORKDIR

COPY ./ $WORKDIR/

ARG version
ENV COMMITID=$version

RUN pnpm install
RUN pnpm build

FROM nginx:alpine as prod

RUN mkdir /fyp_web



COPY --from=builder /fyp_web/dist /fyp_web
COPY --from=builder /fyp_web/docker/nginx.conf /etc/nginx/nginx.conf
#add the cert ssl

# COPY --from=builder /fyp_web/docker/password.txt /etc/nginx/password.txt
# COPY --from=builder /fyp_web/docker/cert.pem /etc/nginx/cert.pem
# COPY --from=builder /fyp_web/docker/key.key /etc/nginx/key.key


EXPOSE 80
