/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true
    }
  },
  {
    name: 'control-panel',
    path: '/control-panel',
    component: 'layout.base$view.control-panel',
    meta: {
      title: 'control-panel',
      i18nKey: 'route.control-panel',
      icon: 'ic:round-dashboard'
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true
    }
  },
  {
    name: 'record',
    path: '/record',
    component: 'layout.base$view.record',
    meta: {
      title: 'record',
      i18nKey: 'route.record',
      icon: 'ic:round-videocam'
    }
  },
  {
    name: 'robot',
    path: '/robot',
    component: 'layout.base$view.robot',
    meta: {
      title: 'robot',
      i18nKey: 'route.robot',
      icon: 'ic:round-android'
    }
  },
  {
    name: 'robot-map',
    path: '/robot-map',
    component: 'layout.base$view.robot-map',
    meta: {
      title: 'robot-map',
      i18nKey: 'route.robot-map'
    }
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base$view.user',
    meta: {
      title: 'user',
      i18nKey: 'route.user',
      icon: 'ic:round-person'
    }
  }
];
